MRTR - dodanie możliwości ustanowienia połaczenia z siecią bezprzewodową

diff --git a/mrtr/mrtr b/mrtr/mrtr
--- a/mrtr/mrtr
+++ b/mrtr/mrtr
@@ -34,9 +34,10 @@ function help() {
   echo "interface - module for configure and control ethernet and wireless interfaces";
   echo "password  - set password for MRTR pi user";
   echo "service   - start and stop dnsmasq or hostapd services";
-  echo "wlan      - configure a broadcasted wireless network";
+  echo "ap        - configure a broadcasted wireless network";
   echo "dhcp      - configure a dhcp service. More info DHCP section.";
   echo "openvpn   - configure a openvpn (client role) service";
+  echo "wlan      - establish connection with wireless LAN network";
   echo;
   echo "INTERFACE:";
   echo "  $ mrtr interface <ethX/wlanX> <IP address/dhcp>";
@@ -56,8 +57,8 @@ function help() {
   echo "  This subcommand it's a pretty alias for systemctl start and stop";
   echo "  actions. For now supports only 3 services and 2 actions.";
   echo;
-  echo "WLAN:";
-  echo "  $ mrtr wlan";
+  echo "AP:";
+  echo "  $ mrtr ap";
   echo "    <ssid> <wlan_network_name>";
   echo "    <mode> <a|b|g> (Warning! Mode 'a' for RPi 3B+ only.)";
   echo "    <channel> <1-13>";
@@ -84,6 +85,13 @@ function help() {
   echo "  $ mrtr netsum";
   echo "  Run a netsum script (print a huge information about network";
   echo "  configuration)";
+  echo;
+  echo "WLAN:";
+  echo "  $ mrtr wlan";
+  echo "    <scan>";
+  echo "    <connect> <essid> [psk]";
+  echo "  If you are trying connect to previous networks, ESSID is everything";
+  echo "  that you need to put";
 }
 regexForIP='[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
 
@@ -129,7 +137,7 @@ if ping -q -c 1 mrtr.local > /dev/null 2>&1; then
                       ssh pi@mrtr.local "sudo systemctl $action ${2}.service";
                   fi
                  fi;;
-      'wlan') ssh pi@mrtr.local "if [ -f /etc/hostapd/hostapd.conf ]; then exit 0; else exit 1; fi";
+      'ap') ssh pi@mrtr.local "if [ -f /etc/hostapd/hostapd.conf ]; then exit 0; else exit 1; fi";
                   if [ $? -eq 0 ]; then
                     #scp pi@mrtr.local:/etc/hostapd/hostpad.conf /tmp/hostapd.conf;
                     fetch /etc/hostpad/hostapd.conf /tmp/hostapd.conf;
@@ -287,6 +295,29 @@ EOF
                   ssh pi@mrtr.local "sudo netsum -o stdout";
                 else echo "Netsum tool not found";
                 fi;;
+      'wlan') ssh pi@mrtr.local "if [ -x /usr/local/bin/wlanconn ]; then exit 0; else exit 1; fi"; 
+              if [ $? -eq 0 ]; then
+                if [ "$2" ]; then
+                  case $2 in
+                    'scan') ssh pi@mrtr.local "wlanconn list";;
+                    'connect') if [ "$3" ]; then
+                                if [ "$4" ]; then
+                                  ssh pi@mrtr.local "wlanconn $3 $4";
+                                else
+                                  ssh pi@mrtr.local "wlanconn $3";
+                                fi
+                               else
+                                help;
+                                exit 1;
+                               fi; 
+                  esac
+                else
+                  help;
+                  exit 1;  
+                fi
+              else
+                echo "Wlanconn tool not found";
+              fi;;  
     esac
   else
     help;
